# Generated by Django 5.2.14 on 2026-08-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accommodationsearch_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are_title', models.CharField(default='Welcome to Uniqix Pte Ltd', max_length=255)),
                ('who_we_are_text', models.TextField(default='Uniqix Pte Ltd is a Singapore-based company specializing in aggregating the procurement of products and services for more than 23 industries, fostering a merit savings and technology transformation for our clients.')),
                ('stat_industries', models.CharField(default='23+', max_length=100)),
                ('stat_partners', models.CharField(default='100+', max_length=100)),
                ('stat_headquarters', models.CharField(default='Singapore', max_length=100)),
                ('stat_global_network', models.CharField(default='50+ Countries', max_length=100)),
                ('stat_trusted_partners', models.CharField(default='500+', max_length=100)),
                ('stat_solutions_delivered', models.CharField(default='10K+', max_length=100)),
                ('stat_years_excellence', models.CharField(default='7+', max_length=100)),
                ('vision_text', models.TextField(default='To become the biggest B2B Procurement Aggregation Platform in Asia Pacific.')),
                ('mission_text', models.TextField(default='To continuously identify our clients’ procurement needs and source for the best quality and most value-for-money products and services to match those needs.')),
                ('incorporation_date', models.CharField(default='26 July 2016 in Singapore', max_length=255)),
                ('uen_number', models.CharField(default='201620244N', max_length=100)),
                ('registration_type', models.CharField(default='Exempt Private Company Limited by Shares', max_length=255)),
                ('principal_activity', models.TextField(default='Retail sale of other household utensils and equipment n.e.c.')),
            ],
        ),
    ]
