# Generated by Django 5.2.14 on 2026-08-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='badge',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='caseNum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='metricsTitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='metrics_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='outcomes_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='quote',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='zones_json',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
    ]
