# Generated by Django 5.2.14 on 2026-08-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_casestudy_author_casestudy_badge_casestudy_casenum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('action', models.CharField(default='Explore Services', max_length=255)),
                ('target', models.CharField(default='services', max_length=100)),
                ('color', models.CharField(default='#2563eb', max_length=100)),
                ('img', models.TextField(default='')),
                ('features_json', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_title', models.CharField(default='What Defines Uniqix ?', max_length=255)),
                ('intro_text_1', models.TextField(default='Uniqix Pte Ltd is a Singapore-based company specializing in aggregating the procurement of products and services for more than 23 industries, focusing on cost savings and technology transformation for our clients.')),
                ('intro_text_2', models.TextField(default='By integrating physical shipping operations, rigid compliance, and direct-from-manufacturer pricing structures, we eliminate high-margin intermediaries and supply chain vulnerabilities.')),
                ('stat1_target', models.CharField(default='$580M+', max_length=100)),
                ('stat1_label', models.CharField(default='Commodities Traded', max_length=255)),
                ('stat2_target', models.CharField(default='40+', max_length=100)),
                ('stat2_label', models.CharField(default='Dormitory Hubs', max_length=255)),
                ('stat3_target', models.CharField(default='100%', max_length=100)),
                ('stat3_label', models.CharField(default='Assay Traceability', max_length=255)),
                ('stat4_target', models.CharField(default='80k+', max_length=100)),
                ('stat4_label', models.CharField(default='Workers Housed', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('initials', models.CharField(default='CS', max_length=10)),
                ('color', models.CharField(default='var(--primary)', max_length=100)),
            ],
        ),
    ]
