# Generated by Django 5.2.14 on 2026-08-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_coredivision_deploymenttelemetry_homepagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('bullets_json', models.TextField(default='[]')),
                ('action', models.CharField(default='dormitories', max_length=100)),
                ('actionText', models.CharField(default='Search Accommodation Hub', max_length=255)),
                ('themeColor', models.CharField(default='#D4A72C', max_length=100)),
                ('badgeBg', models.CharField(default='rgba(197, 160, 89, 0.1)', max_length=100)),
            ],
        ),
    ]
